flags: {}
packages:
- '.'
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.20160414_ghc-7.10.3:
        url: https://s3.amazonaws.com/ghcjs/ghcjs-0.2.0.20160414_ghc-7.10.3.tar.gz
        sha1: 6d6f307503be9e94e0c96ef1308c7cf224d06be3

compiler-check: match-exact
compiler: ghcjs-0.2.0.20160414_ghc-7.10.3
resolver: lts-6.1

extra-deps:
- reflex-0.4.0
- reflex-dom-0.3
- ref-tf-0.4.0.1